### ISSUE TITLE
Hanging on thrustcurve import

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#1167]
see https://www.rocketryforum.com/threads/announcement-openrocket-version-22-02-public-beta-is-underway-download-it-now.171295/post-2246069

**Comment by JoePfeiffer** [comment]
https://www.rocketryforum.com/threads/announcement-openrocket-version-22-02-public-beta-is-underway-download-it-now.171295/post-2246136

**Comment by SiboVG** [comment]
FYI: this is the bug that's happening (replicated on the Windows 11 Parallels Desktop virtual machine on my MacBook). A white window that's completely unresponsive.
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/11031519/195414723-0208aa10-fffd-4607-bd89-c9f9ec6ade8f.png">

**Comment by JoePfeiffer** [comment]
Thanks for reminding me of this -- for some reason I was thinking it had been resolved, but clearly not.  Could you post the thrustcurve file causing the issue?

**Comment by SiboVG** [comment]
The problem doesn't originate from the thrustcurve, I just picked a random curve from thrustcurve s.org and edited it to have 2 different-valued thrust values at same time instances. It's an issue with window modality on some machines. Last time I researched this issue I think it had something to do with multithreading with modality, because there are 2 windows with modality open at the same time.


________________________________
