### ISSUE TITLE
Rocksim import miniaturizes fins

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#1220]
Reported here: https://www.rocketryforum.com/threads/announcement-openrocket-version-22-02-public-beta-is-underway-download-it-now.171295/post-2249624
[8 in Goblin 4 x 75mm.zip](https://github.com/openrocket/openrocket/files/8188751/8.in.Goblin.4.x.75mm.zip)

In Rocksim:
![image](https://user-images.githubusercontent.com/243872/156841423-cc0e8bfc-bda4-410b-be9d-ef62cb605b6a.png)

After import to OR:
![image](https://user-images.githubusercontent.com/243872/156841448-d3cfb6e1-2a03-4663-9711-56f563564051.png)

**Comment by hcraigmiller** [comment]
I'm not sure this is an OpenRocket problem. If I strip the AGM down to the outer frame (and removing fin tabs) in Rocksim 10, then save it to a new file, and import that into OpenRocket, then the fins shrink.

If I take the stripped AGM in Rocksim 10, delete the back fins, and recreate identical back fins, then import into OpenRocket, only the front fins shrink.

If I take that in Rocksim 10, delete the front fins, and recreate identical front fins too, then import into OpenRocket, none of the fins shrink shrink.

![Compare 1000px](https://user-images.githubusercontent.com/68821492/156855916-47c4a91a-f86b-4eb4-92ef-9047803c4222.png)

This may be an issue within Rocksim versions. But, still playing with it.

**Comment by neilweinstock** [comment]
It seems to me that if, in any circumstance, the same RKT file looks different after import into OR than it does in Rocksim, then it's an OR problem.

I note that not only are the Goblin fins miniaturized, they are also the wrong shape.  In the Rocksim file there's a point list that looks like this:

`<PointList>329,0|379,277|151,370|0,0|0,0|0,0|0,0|0,0|0,0|0,0|</PointList>`

That definitely describes those huge Goblin-shaped fins (measurements in mm), but the OR importer is somehow mangling them into tiny parallelograms.

**Comment by hcraigmiller** [comment]
I would disagree somewhat. If an old Rocksim file is not currently formatted correctly (because of no longer used code or otherwise), but when created in the current Rocksim version it works correctly, then that is a Rocksim problem, not an OpenRocket problem.

That said, I do agree that identification of the problem (comparing the data pre and post fin recreation) is needed to validate the conclusion (or improve OpenRocket conversion if appropriate). I am undertaking that now.

**Comment by neilweinstock** [comment]
If Rocksim can read it, then we should be able to read it. Obviously there are practical limits to this, but in this case the correct data is there in the file, plain as day.

**Comment by hcraigmiller** [comment]
Okay, this is not an OpenRocket problem, it is a Rocksim problem. Rocksim is intermittently adding additional points to the points list. Rocksim sometimes saves the file with too many |0,0| point sets, to such an extent that it is incompatible with OpenRocket. 

For example: <PointList>329,0|379,277|151,370|0,0|0,0|0,0|0,0|0,0|0,0|0,0|</PointList> should be <PointList>329,0|379,277|151,370|0,0|</PointList>
 
Everything after the first |0,0| point should be deleted. Although OpenRocket can handle two |0,0| points, instead of one, when the third is added OpenRocket shrinks the fins.

If the OpenRocket import conversion truncates anything after the first {0,0} point, it should work reliably.
