### ISSUE TITLE
plot scaling is based only on sustainer, not booster.

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#1228]
If the booster somehow manages to go higher than the sustainer, its plot isn't scaled correctly. Yes, this does require a bad flight configuration, but we should still do the right thing with it.
![bad-plot](https://user-images.githubusercontent.com/3065196/157083586-6e1c4837-dd69-43b5-b8bf-70469d7f9818.png)
The rocket that did this is here.
[Pod-Boosters.ork.txt](https://github.com/openrocket/openrocket/files/8199551/Pod-Boosters.ork.txt)

**Comment by SiboVG** [comment]
Seeing the plot, should we also file a new feature request to add distinction between different stage plots? So e.g. the altitude-plot of the booster stage remains the same blue, but with a dashed line instead of a solid line. Looks a bit messy otherwise if you have the same line styles for different data sets...

**Comment by JoePfeiffer** [comment]
The current approach (you can view all the data sets or any one of them) seems to work well enough for me.
