### ISSUE TITLE
"fit" doesn't always work in side view

### ISSUE THREAD

**Issue by sjh114961** [openrocket/openrocket#1231]
"fit" doesn't always work in side view. The ends sometimes go off screen and you can pan over to see end. See exampl
[sjh_trident.zip](https://github.com/openrocket/openrocket/files/8200848/sjh_trident.zip)
e

**Comment by hcraigmiller** [comment]
The problem presented is that _Inner Components_ which extend beyond the "airframe" are not included in the length of the rocket for the purpose of calculating the overall rocket length (shown in the upper left of the display window), determining the size of the display window, or otherwise.

The collateral issue raised by this issue is how to adjust the flight characteristics computation to take into account inner components extending into the airflow.

**Comment by JoePfeiffer** [comment]
The basic problem here is that this model has an "inner" tube that's partially external.  The best fix for it would be to replace it with an inner tube that reached to the end of the body tube, and then a body tube with the same diameter extending from there.

Modifying the "fit" function so it looked at all components, internal and external, for its calculations would be reasonable. I *really* don't want to get in to inferring what parts are and are not exposed to the airflow for simulations.

**Comment by hcraigmiller** [comment]
>Modifying the "fit" function so it looked at all components, internal and external, for its calculations would be reasonable.

I too think this is the best approach. Those wanting airflow analysis can use _Body Components_ instead of _Inner Components_. Kind of the best of both worlds.

**Comment by sjh114961** [comment]
This still seems to be a problem in beta 2

**Comment by neilweinstock** [comment]
> Modifying the "fit" function so it looked at all components, internal and external, for its calculations would be reasonable.

I vote a hearty "aye" to this.  I'm a bit confused why it would do anything else?
