### ISSUE TITLE
Java 11 v Java 17

### ISSUE THREAD

**Issue by gri2a** [openrocket/openrocket#1274]
I was happy testing OpenRocket22 in Java 17 (I was also testing in Java 11), however with beta release2 youve restricted it purely to Java 11. If you want to move forward with future releases of Java... isnt this a retrograde step??
GRI2A

**Comment by SiboVG** [comment]
We pushed a commit 2 days ago that allows Java 11 and Java 17 execution. We are now in the process of testing if issues appear in Java 17 that do not appear in Java 11.

We choose sole Java 11 execution because we noticed some bug reports that were JRE-specific (e.g. Java 14 and Java 15 produced some bugs).

But yes, the goal is to make OR run in Java 17 as well.
