### ISSUE TITLE
FreeForm Fin weight calculation is different between 1503 and ver 22 beta 2

### ISSUE THREAD

**Issue by sjh114961** [openrocket/openrocket#1324]
[L3 v3.zip](https://github.com/openrocket/openrocket/files/8599934/L3.v3.zip)

 There is indeed a difference. and the only difference is in the freeform fins weight. The 1503 version thinks its 33.6 oz and ver 22 thinks it is 40.8 oz. My manual calculation says 36 774 oz.

**Comment by hcraigmiller** [comment]
While it is true that 15.03 and the current unstable differ, that is because there was an error in the 15.03 calculation. Here is a spreadsheet showing that the error is in the 15.03 fillet volume computation.

![Computation_Fin_Mass](https://user-images.githubusercontent.com/68821492/166442899-d98a3dfa-8d9e-4898-ab47-fead744d68c6.png)

The difference appears to be the result of the correction of a 15.03 bug, not a bug in the current unstable.

Recommend confirm and close.

**Comment by sjh114961** [comment]
Thank you very much for confirm our suspicion. I had someone run the model through RockSim and got the same result.
