### ISSUE TITLE
Show drag coefficient values with more precision

### ISSUE THREAD

**Issue by Mudrost** [openrocket/openrocket#1441]
When displaying the component drag contribution, the default number of decimal places is 2. 
![image](https://user-images.githubusercontent.com/20509814/173451418-49ef268e-672f-48a9-b0df-adbabeeb7e55.png)
The only way to see more decimal places is to press Ctrl + C at the line you want, then paste it somewhere...
![image](https://user-images.githubusercontent.com/20509814/173451540-f0ecd28e-b829-4c91-872d-ebf5a99ec96f.png)

Suggestion: add a dropdown list for no. of decimal places.

**Comment by SiboVG** [comment]
I've put up PR #1476 that increases the resolution to 3 decimals instead of the previous 2.

The discussion of allowing custom decimal settings with a sort of dropdown list is one that's already been active (e.g. [here](https://github.com/openrocket/openrocket/issues/999#issuecomment-1025839025)). But it's not an easy discussion because of which other fields would be affected by the decimal point change etc., so for now I'll just keep it at increasing the resolution to 3 decimals. But custom decimal point edits is something we're planning on eventually implementing.
