### ISSUE TITLE
[Bug] Side view centering not correct when child component goes outside of parent

### ISSUE THREAD

**Issue by sjh114961** [openrocket/openrocket#1465]
Fit in side view still broken. See ork and image

[Mercury.zip](https://github.com/openrocket/openrocket/files/8935898/Mercury.zip)
![MercuryFit](https://user-images.githubusercontent.com/53155232/174490448-c64b3193-73ce-4527-99dc-e7ec74cb048d.png)

**Comment by hcraigmiller** [comment]
The centering issues appears to be 2D related...

![2D-3D](https://user-images.githubusercontent.com/68821492/174492882-9339d2d5-83ee-491f-87c1-1c9ef1758da1.png)

It never ceases to amaze me as to what pods are used for...

**Comment by SiboVG** [comment]
This issue seems to be caused by pods. For example if you open 'A simple model rocket', delete the nose cone, put a pod set in the body tube, a nose cone in that pod set and move the pod set to the beginning of the body tube, the centering is not done correctly.

**Comment by hcraigmiller** [comment]
Agreed... if you rearrange the components in the Mercury.ork so that the red nose cone is the first component then the centering is correct. Just interesting that the 3D displays correctly and the 2D does not.

**Comment by hcraigmiller** [comment]
Part of the problem lies in the fact that the designs that are being complained of cannot be constructed in the real world. Using this design, for example, the red tip is constructed using a nose cone, and three body tubes. However, there is no transition between the first small diameter body tube and the second (much larger diameter) body tube, leaving the first hanging in the air without any support.

![Tip](https://user-images.githubusercontent.com/68821492/174493919-9d23c324-52d0-4d8c-b583-9fdf077cdde7.png)

But, I do agree that the 2D display should account for the extent of the pod components.

**Comment by sjh114961** [comment]
I tried to do the fix as described above and could not make it work. Could someone attach the fixed ORK here so I can see what was done.

**Comment by SiboVG** [comment]
> I tried to do the fix as described above and could not make it work. Could someone attach the fixed ORK here so I can see what was done.

Changing the ORK will not solve the issue, but I merged a PR yesterday that fixes the issue. If you want to play around with it, [here is the JAR file](https://github.com/openrocket/openrocket/suites/6999543371/artifacts/274446489) with the fix.

**Comment by sjh114961** [comment]
Yes, this jar file seems to work correctly.Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
