### ISSUE TITLE
[Bug] Old simulation re-runs when new simulation is created with same motor eventhough "run-outdated" off

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1510]
See TRF discussion about [preserving outdated simulation data](https://www.rocketryforum.com/threads/announcement-openrocket-version-22-02-public-beta-4-is-now-available.171295/page-18#post-2294522); **restores v15.03 behavior**. And, [current behavior](https://www.rocketryforum.com/threads/announcement-openrocket-version-22-02-public-beta-4-is-now-available.171295/page-18#post-2294520).

![Sym_NC_Cd 05](https://user-images.githubusercontent.com/68821492/177105660-ea2f6085-f949-4ab8-b8ff-f23911289a93.png)
[Test Rocket 29mm motor minimum fin v22.Rev_02.ork.txt](https://github.com/openrocket/openrocket/files/9037329/Test.Rocket.29mm.motor.minimum.fin.v22.Rev_02.ork.txt)

**Comment by SiboVG** [comment]
I don't exactly see the point of this issue request?

The current behavior is: if a certain flight configuration is selected, even when the 'run out-dated' is turned off, OR makes sure all simulations with that configuration are up-to-date. When you create a new simulation and change the flight configuration of that sim, you also update the currently selected configuration of the rocket (see flight configuration combo box above the rocket view). So in your example, changing the new simulation's flight configuration to 'G80-10' updates the rocket's selected configuration to 'G80-10', and, because Simulation 1 with flight config 'G80-10' is not up-to-date, OR updates simulation 1.

So is that regard this issue is rather: **don't change the currently selected rocket configuration when changing the configuration of a simulation?**
