### ISSUE TITLE
[Bug] When summary data is saved for sims, reading the .ork doesn't always pick it up.

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#2067]
**Describe the bug**
~~If we try to save a sim with the "only primary figures" option checked, not all simulation summaries are saved~~
When we save a sim with the "only primary figures" option checked, the data is saved but reading the .ork file later doesn't always get it.

**To Reproduce**
Start OR
Open "simple model rocket" example
Run simulations
Save to a new file with "only primary figures" option set
Close and reopen OR
Load the saved .ork
Observe summary table isn't fully populated
![summary-table](https://user-images.githubusercontent.com/3065196/220706763-762539da-87d7-45d7-8f7e-700a23052a1b.png)

**Expected behavior**
All rows in summary table should have been populated

**Comment by SiboVG** [comment]
May I also add that the term "Only primary **figures**" sounds very confusing? When I hear the word "figures", I think of graphs, not the numbers in the sim table. May be because I'm not a native speaker, but I had a very different notion of the intended behavior of that save function... (don't know what the behavior of "Only primary 'graphs'" would be, but in any case I find "figures" confusing)

**Comment by JoePfeiffer** [comment]
> May I also add that the term "Only primary **figures**" sounds very confusing? When I hear the word "figures", I think of graphs, not the numbers in the sim table. May be because I'm not a native speaker, but I had a very different notion of the intended behavior of that save function... (don't know what the behavior of "Only primary 'graphs'" would be, but in any case I find "figures" confusing)

Yes.  I'm thinking of changing it to "summary data" while I'm at it.
