### ISSUE TITLE
Tube decal should not be applied to the edge

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#2107]
For tubes (Body or Inner), OR22.02 is applying the decal image, if any, to the ends of the tube.  As far as I can tell, OR15.03 did not do this.

Here is a comparison of 15.03 (left) and 22.02 (right), showing the effects of this (ORK file is attached):
![image](https://user-images.githubusercontent.com/243872/224039262-f8671f8a-7045-44df-b698-ab613697eaba.png)

Until something more intelligent can be done, only the color of the tube should be applied to the ends, not the decal.

[tube-test.zip](https://github.com/openrocket/openrocket/files/10932119/tube-test.zip)

**Comment by hcraigmiller** [comment]
In clarification, 15.03 did not allow separate inner and outer appearance settings, which are now allowed, including setting the edge to either the inner or outer color. 

![Decals Rev_01](https://user-images.githubusercontent.com/68821492/224146240-de3e93fd-26fd-4cd5-af21-337b7c8acbdf.png)

My concern, and where I think the bug is, is that the edge has any decal coverage at all in this situation:

![Decals Rev_02](https://user-images.githubusercontent.com/68821492/224148661-75a5e5a8-00bf-4ce3-b10f-b5c05e13154b.png)

**Comment by neilweinstock** [comment]
> My concern, and where I think the bug is, is that the edge has any decal coverage at all in this situation:

Correct.
