### ISSUE TITLE
Программа исправляет данные в ракете и сбрасывает нужные

### ISSUE THREAD

**Issue by anbrightny** [openrocket/openrocket#2515]
Добрый день. Программа Open Rocket при указывание данных ракеты (внутреннего диаметра и толщины стенки) обнуляет данные и ставит свои. Подскажите, пожалуйста, как это можно устранить?

**Comment by SiboVG** [comment]
> Good afternoon. The Open Rocket program, when specifying rocket data (internal diameter and wall thickness), resets the data and enters its own. Please tell me how this can be fixed?

Hello, this is intentional design. For a body tube, you can set the outer diameter and the inner diameter or the wall thickness. For example, if you set the outer diameter to 10 cm and the inner diameter to 9 cm, then the wall thickness will automatically be set to 0.5 cm (10 cm - 9 cm, divided by 2). If you set the outer diameter to 15 cm and the wall thickness to 1 cm, then the inner diameter will be 13 cm (15 cm - 2 * 1 cm).

In other words, the inner diameter and wall thickness are 2 different widgets that have the same effect. If you change one, the other will be updated.
