### ISSUE TITLE
IllegalStateException when creating multiple launch lugs

### ISSUE THREAD

**Issue by radio-satellites** [openrocket/openrocket#2556]
---------- Bug report ----------

Please include a description about what actions you were performing when the exception occurred:
(You can edit text directly in this window)

1. Create body
2. Add components
3. Add launch lug
4. Try adding anything else

If possible, please send us the .ork file that caused the bug.

Full stack trace here: https://pastebin.com/QX3qbF4K

**Comment by SiboVG** [comment]
Hello,

Thank you for your report. This bug has been resolved and will be fixed in the next release.

Cheers,
Sibo

From: radio-satellites ***@***.***>
Date: Saturday, 7 September 2024 at 02:49
To: openrocket/openrocket ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [openrocket/openrocket] IllegalStateException when creating multiple launch lugs (Issue #2556)

---------- Bug report ----------

Please include a description about what actions you were performing when the exception occurred:
(You can edit text directly in this window)

  1.  Create body
  2.  Add components
  3.  Add launch lug
  4.  Try adding anything else

If possible, please send us the .ork file that caused the bug.

Full stack trace here: https://pastebin.com/QX3qbF4K
