### ISSUE TITLE
Improve the Scale Dialog

### ISSUE THREAD

**Issue by SpamWall** [openrocket/openrocket#411]
Based on an email from Joe Pfeiffer:

- [ ] 1. the "Scaling to apply" window is only three digits, allowing only a factor of 999% to be displayed.  Putting in a wider number is possible, but requires scrolling back and forth in the window to see.  
- [ ] 2. The Scale from and to windows are only one digit wide (though after I've scaled a rocket, they get wider?).
- [x] 3. When I apply a scale factor, it doesn't recenter the rocket in the window, and doesn't bring up scrollbars.  The result is that the rocket disappears on a large scale.
- [ ] 4. The dialog presents scaling in terms of %, but the error dialog presents it in terms of scale factor.  I actually like scale factor better, but they both need to be one or the other

**Comment by teyrana** [comment]
re: Item 3:
a) It should recenter.  The fact that it doesn't is a bug, and may be due to a missing message pass from the scale code to the RocketFigure.
b) Figure bounds are assumed to always go from 0 to max-rocket-extent.  This works well enough, normally..... but is problematic in the corner cases.  Would love to see a patch for that, too :)

**Comment by teyrana** [comment]
re: item 3:
Unrelated fixes to the rocket figure may resolved that issue. 
TODO:  check this.
