### ISSUE TITLE
Alpha 10: spurious thick fin warning

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#497]
In Alpha 10 I am seeing a spurious thick fin warning when fins are inside pods.  In this design for instance:
![image](https://user-images.githubusercontent.com/243872/49832792-afeeff00-fd65-11e8-9861-1f13eca256f0.png)

the fin extensions on the outside are attached to phantom tubes attached to pods.  They are 3/32" thick, definitely not thick.  Deleting those fins makes the thick fin warning go away.

[thick_fins.zip](https://github.com/openrocket/openrocket/files/2669606/thick_fins.zip)

**Comment by teyrana** [comment]
So, it turns out, it's due to the Phantom body tube.  The warning is generated if the fin is thicker than half of it's parents radius.  This would be relatively easy to fix if we can decide what that measure should *actually* be.

Given that this case already involves non-physical components:  If some user is using phantom tubes, they're already well off the reservation.  Let's just assume they know what they're doing, and can fend for themselves.  This is what the proposed fix PR does -- disable warnings for fins on phantom tubes.
(see: https://github.com/openrocket/openrocket/pull/535)

see: https://github.com/openrocket/openrocket/blob/unstable/core/src/net/sf/openrocket/aerodynamics/barrowman/FinSetCalc.java#L104
``` java
	// Add warnings  (radius/2 == diameter/4)
	if (thickness > bodyRadius / 2) {
		warnings.add(Warning.THICK_FIN);
	}
```

**Comment by neilweinstock** [comment]
It is a good change to ignore phantom body tubes when simulating.  I would apply it to zero-length as well; they are sometimes needed and often cause spurious diameter discontinuity errors (a separate issue from this one, but since phantom body tubes came up...

**Comment by teyrana** [comment]
Ahhhh, to be exact, warnings =/= sim.

The simulation probably already trivially ignores zero length/zero diameter
components, but that may or may not still emit warnings.

Do you happen to have an .ork which throws the warning?

**Comment by teyrana** [comment]
Appears to have evolved to #571
