### ISSUE TITLE
3d Rendering errors cause unending bug report loop

### ISSUE THREAD

**Issue by bkuker** [openrocket/openrocket#82]
When a rendering error causes a bug report popup, if dismissing that pop-up causes the 3d view to re-render, causing a bug report popup.

**Comment by JoePfeiffer** [comment]
Has anyone duplicated this recently?

**Comment by hcraigmiller** [comment]
I have tried numerous scenarios trying to trigger an error so that I could verify this issue, but I have been unable to get an error to test. The only potential bug I have discovered is that the "Smoke" function on the "Effects" tab seems to be inoperable. Insofar as I can discern, checking and unchecking the smoke function, and increasing and decreasing the value, has absolutely no effect on the display.

**Comment by hcraigmiller** [comment]
The only other problem, which I view as significant, is that 3D functions on my system are not shown at the resolution set for my display. This is a change from 15.03. Using the sample Apocalypse rocket, you can see the problem.

![Sample 01](https://user-images.githubusercontent.com/68821492/101810948-4332aa80-3ace-11eb-8291-e7fb12ddd569.png)
![Sample 02](https://user-images.githubusercontent.com/68821492/101810962-47f75e80-3ace-11eb-8c0e-012339d9db2e.png)

Although not recognizing the system display settings for 3D functions is not otherwise affecting program functionality, when the Beta is release this bug will likely trigger a host of reports.

**Comment by JoePfeiffer** [comment]
If nobody can replicate the original error, perhaps we should close this?  The difference in scale seems like a different issue, and not one that should delay us.

**Comment by hcraigmiller** [comment]
I agree that this issue should be closed at this point.

**Comment by wolsen** [comment]
I have seen this unintentionally while working on a change. Ultimately the bug in my code caused this and I have not been able to see it "naturally". I will close this out for now and should someone encounter this again, we can reopen it.
