### ISSUE TITLE
Trapezoidal fin sets: default count is "1", should be "3"

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#850]
I feel like this was fixed in the past, but it's still showing up.  When creating a new trapezoidal fin set, the default count is "1".  It should be "3".

**Comment by wolsen** [comment]
So it looks like the default for all fin types *except* trapezoidal fin set is 3. The trapezoidal fin set count was set to default to 1 with the change for issue #431. Will need to revisit that fix. The fix to default to 3 is trivial, but need to ensure not to re-introduce the issue in 431.

**Comment by wolsen** [comment]
Okay, reviewing the file attached to #431 it appears that the issue was with the way the file was saved. The number of fins (instancecount) was not saved within the file when it was saved. Therefore, when the file was opened it defaults to whatever is set as the default. That default was changed down from 3 to 1 to initially fix the issue, however it was the persistence of the instancecount for the finset that actually resolves the problem.

This means that it is likely that there are a few files here and there where the instancecount is not saved as part of the .ork file and opening those up will get the default value. The design should be reconfigured to have the correct number of fins and then saved in order to persist this.

With this, I think the right change is to simply revert the trapezoid default finset count back to 3.

**Comment by neilweinstock** [comment]
That sounds reasonable.
