### ISSUE TITLE
Enable window to be narrower

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#898]
There are many occasions when I want the OR window to be fairly small, so I can have it open side-by-side with either another design(s) or an image editor while i'm working on decals.  Right now, the narrowest the layout can get before it starts clipping is shown here:
![image](https://user-images.githubusercontent.com/243872/110411748-17857900-8059-11eb-99e5-7b2c1938ac70.png)

When there are multiple stages its worse, because the stage buttons are laid out horizontally and make the minimum window width even larger.

It looks to me like the limit it being set by the display area.   Within that area, there are two bits of GUI that are consuming excessive horizontal space:  the text "View type" and "Flight configuration".  Arguably "View type" is redundant, since the selected option describes itself as a view.  I'm not sure about "Flight configuration".  Probably need some sort of label for that.

If we can't get rid of the text, then maybe when the window gets sufficiently narrow the text could stack on top of the selector or something?

If I can think of a more coherent suggestion of what I would like to see done, I'll add it here; in the meantime I just wanted to log the issue for future consideration.

**Comment by hcraigmiller** [comment]
I agree with @neilweinstock that the information above the display window could be condensed somewhat so that side-by-side programs can be run. This could be done by:

1. Changing the text "View type" to simply "View." Doing so preserves the word "view" for those selections not containing that word (the 3D views) and allows the selection box to be lined up with the view window ruler on the left side.
2. Making the selection/magnification buttons square (shortening the width).
3. Making the distance between the stage button and the percentage selection/magnification button the same as between the percentage display and the percentage selection/magnification button.
4. Changing the text "Flight configuration" to "Configuration"; from a consistency standpoint, the word "flight" should be "motor" (as used on the tab) anyway. To condense the text further, the word "Config" or "Motor" or "Layout" (or another short word) could be used instead of "Configuration." 

These adjustments allow two one-half screens to be side-by-side without clipping.
![Display Window Upper Text 010](https://user-images.githubusercontent.com/68821492/111001556-de8b2400-8338-11eb-96cd-a6aa470cc700.png)

**Comment by neilweinstock** [comment]
Those are good suggestions.

As a minor side note, "Side view" and "Back view" should really be shortened to simply "Side" and "Back", since the word View is already there on the left.  It doesn't make the window any narrower, because the pull-down width is determined by "3D Unfinished", but it would be a bit more "correct" IMHO.
