### ISSUE TITLE
"Motor mounts" list in "Motors and Configurations" tab is pointlessly small

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#902]
The "Motor mounts" list is pointlessly small, not filling up the available space.  As a result, it often looks like this:
![image](https://user-images.githubusercontent.com/243872/110725184-28fb8c00-81e5-11eb-9a29-1d95955817f0.png)

I can't think of any reason all the space should be wasted on the left.  The Motor Mounts list should occupy the same vertical space that the configuration list does, and it should fill the available horizontal space, too.

**Comment by hcraigmiller** [comment]
For reference, the example below is in Windows 10 [1920 x 1080 display], using the "Three-stage rocket" design file:

![0902](https://user-images.githubusercontent.com/68821492/110857004-2e9cb480-826d-11eb-94ac-2e83e8314bb5.png)

I believe that very few users will ever exceed 3 stages, and even then only infrequently, so the configuration window width could be shortened somewhat so that the motor mounts window width may be lengthened. But, 3 stage rockets are relatively common and the window widths should take that into account.

**Comment by neilweinstock** [comment]
This was fixed by #1098, closing.
