### ISSUE TITLE
Position component relative to tip of nose cone needs to be brought back

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#907]
I hadn't noticed it was gone until K'Tesh posted on the mailing list...

**Comment by neilbalch** [comment]
Wait, sorry... What does this mean in practice? I'm having a hard time conceptualizing the meaning of this bug report. :(

**Comment by hcraigmiller** [comment]
In 15.03, the user has the option of locating an internal part by reference to the "tip of the nosecone." This option does not appear in the current unstable. In designing internal components that are subcomponents of different exterior parts (e.g., two different body tubes), but where the internal components are related to one another in position (e.g., recovery system components that touch or overlap), it is more convenient to position the internal components by referencing the tip of the nosecone instead of the top, bottom, or center of each separate parent component.

**Comment by neilbalch** [comment]
Ah. Forgive me if I'm misunderstanding, but shouldn't this be fairly trivial given that the feature already existed? AFAIK we'd just need to `git blame` to find the commit that removed it and then just submit a PR that reverts the changes made... right? :)

**Comment by hcraigmiller** [comment]
I'm not familiar with the extend of the coding change(s) that resulted in the loss of the option, but a comparison of the old to the current code sounds like a reasonable first step.

**Comment by neilbalch** [comment]
I think my latest PR now addresses this issue.
