### ISSUE TITLE
Active tabs on Mac look just awful

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#948]
When a tab is selected and active in a window, on Mac OS this is displayed as a white tab background with white text with just a little bit of a drop shadow. The white text of the active tab should be replaced by e.g. a black color to give it more contrast compared to the background.

![Screenshot 2021-06-15 at 20 31 13](https://user-images.githubusercontent.com/11031519/122105279-e2878000-ce18-11eb-894b-74cf8c9e0e79.png)

**Comment by wolsen** [comment]
Fairly positive this is a Java bug https://bugs.openjdk.java.net/browse/JDK-8251377

**Comment by wolsen** [comment]
I've put up a jar file [here](https://www.dropbox.com/s/50joo0qdv88gh0i/OpenRocket-theme.jar?dl=0) which has the options of theme selection using jformdesigner's formdev flatlaf stuff.

@neilweinstock @SiboVG care to try it out to see if it fixes some of the selection stuff. Note, there's a couple of nit issues with it that I'm still looking at, thus no PR of any kind.

**Comment by SiboVG** [comment]
> I've put up a jar file [here](https://www.dropbox.com/s/50joo0qdv88gh0i/OpenRocket-theme.jar?dl=0) which has the options of theme selection using jformdesigner's formdev flatlaf stuff.

Well, I really really like the ability to change the theme in the first place!

The Mac OSX theme is no better than system default, but other themes do work and in my opinion look even better than the original. This also adds the possibility for custom themes in the future or dark modes etc.
![image](https://user-images.githubusercontent.com/11031519/125187653-f617e200-e230-11eb-96c7-75ec8ea3bacb.png)
![image](https://user-images.githubusercontent.com/11031519/125187681-12b41a00-e231-11eb-8093-c23ca1bfeb38.png)

**Comment by neilweinstock** [comment]
That is cool, but... I would hope we don't ship it in that form.  There are way too many options, and many of them are either (a) horrible, or (b) too similar to each other.  I don't think that's adding value.

*Especially* since they don't generally solve the problem at hand.  Here's the Motors and Configuraitons tab on either Cyan or Gray (lost track):
![image](https://user-images.githubusercontent.com/243872/125370012-821e2c80-e34b-11eb-9eed-86fe4bf9d9a7.png)

The dark highlight is still being used against black text.  This was true of other themes as well, but I didn't fully examine them all (again, list too long).

**Comment by wolsen** [comment]
@SiboVG if you want to take a look at resolving this issue (since you have a Mac and I don't). There's a similar reported issue against the JDK at https://bugs.openjdk.java.net/browse/JDK-8257595, which if you see there's a work around by using UIManager.put("TabbedPane.foreground", Color.black). You can drop that in GUIUtil.setBestLAF for the MacOS case. While looking at it, I suspect you'd be able to fix #968 in a very similar vein.

**Comment by SiboVG** [comment]
> @SiboVG if you want to take a look at resolving this issue (since you have a Mac and I don't).
Yup, will give it a try

**Comment by SiboVG** [comment]
@wolsen can confirm that this solves the issue.

I do however very much like the idea of custom themes, so I would like to see something like that implemented.

**Comment by neilweinstock** [comment]
> @wolsen can confirm that this solves the issue.

Did you check the motor selection/configurations tab?

**Comment by SiboVG** [comment]
> > @wolsen can confirm that this solves the issue.
> 
> Did you check the motor selection/configurations tab?

Yes, here is an example:
![image](https://user-images.githubusercontent.com/11031519/125859751-613d4fc4-78fa-4a34-8560-2beaaddbb69d.png)

**Comment by neilweinstock** [comment]
Which theme is that?  I couldn't find any that look like that (which is to say, pretty Mac-looking, with proper tab bar)

In any case, what I have seen is that even when the selected motor looks good (white text on dark background), the main Motors and Configurations tab still looks like this ("Gray" theme):
![image](https://user-images.githubusercontent.com/243872/125869313-8752878f-db50-4a03-b9aa-d8b813350ebe.png)

**Comment by wolsen** [comment]
> I do however very much like the idea of custom themes, so I would like to see something like that implemented.

I do too and can polish that up. But honestly, for now, I'm going to switch my attention to higher priority issues for a beta drop. There's a variety of little nits that need to be handled throughout. I pitched it up as an idea before I realized the Mac bits can be fixed with a relatively small change.

> Which theme is that? I couldn't find any that look like that (which is to say, pretty Mac-looking, with proper tab bar)

That should be the actual Mac theme, just with a fix to the Java UIManager settings. Does not require the theme changes jar I provided.

> 
> In any case, what I have seen is that even when the selected motor looks good (white text on dark background), the main Motors and Configurations tab still looks like this ("Gray" theme):

Yeah, for the sake of this issue - let's discard the theme bits and go with where @SiboVG is looking (making some tweaks without themes to fix the coloring on Mac).
