### ISSUE TITLE
Photo Studio sky image empty option should be custom color

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#950]
When picking a sky color in Photo Studio, you can choose different sky images, or pick a custom color. However, the custom color option is just a blank option right now. It's just not that obvious now that you can change the sky color by picking that empty option. Maybe add a checkbox or something else to make it more clear?

![image](https://user-images.githubusercontent.com/11031519/122132470-35722f00-ce3b-11eb-8e8d-bab1cf0cccce.png)

**Comment by hcraigmiller** [comment]
My suggestion would be to clarify/simplify the verbiage.  The selection block is already captioned "Sky" so the use of "Sky Color" and "Sky Image" seems redundant. Perhaps renaming the selection "Sky Color" to "Solid Color" and renaming the selection "Sky Image" to just "Image"  would be more clear; the verbiage "Solid Color" (or "Solid Backdrop" or another label) could also be the first line of the "Image" selection option, instead of no text at all.

Although somewhat beyond the scope of this issue, it would be nice to implement Issue #773, allowing user images as backdrops.
